{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2019-9674",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "python",
            "product": {
              "product_data": [
                {
                  "product_name": "python",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "3.7.2",
                        "version_affected": "<="
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-400"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://bugs.python.org/issue36260",
          "name": "https://bugs.python.org/issue36260",
          "refsource": "MISC",
          "tags": [
            "Issue Tracking",
            "Vendor Advisory"
          ]
        },
        {
          "url": "https://bugs.python.org/issue36462",
          "name": "https://bugs.python.org/issue36462",
          "refsource": "MISC",
          "tags": [
            "Issue Tracking",
            "Vendor Advisory"
          ]
        },
        {
          "url": "https://github.com/python/cpython/blob/master/Lib/zipfile.py",
          "name": "https://github.com/python/cpython/blob/master/Lib/zipfile.py",
          "refsource": "MISC",
          "tags": [
            "Third Party Advisory"
          ]
        },
        {
          "url": "https://python-security.readthedocs.io/security.html#archives-and-zip-bomb",
          "name": "https://python-security.readthedocs.io/security.html#archives-and-zip-bomb",
          "refsource": "MISC",
          "tags": [
            "Vendor Advisory"
          ]
        },
        {
          "url": "https://security.netapp.com/advisory/ntap-20200221-0003/",
          "name": "https://security.netapp.com/advisory/ntap-20200221-0003/",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://www.python.org/news/security/",
          "name": "https://www.python.org/news/security/",
          "refsource": "MISC",
          "tags": [
            "Vendor Advisory"
          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Lib/zipfile.py in Python through 3.7.2 allows remote attackers to cause a denial of service (resource consumption) via a ZIP bomb."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe_match": [
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "3.7.2"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 5.0
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 10.0,
      "impactScore": 2.9,
      "acInsufInfo": false,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2020-02-04T15:15Z",
  "lastModifiedDate": "2020-02-24T17:15Z"
}